### ISSUE TITLE
Download from routeviews via HTTP additional to FTP

### ISSUE THREAD

**Issue by wagner-certat** [hadiasghari/pyasn#64]
Currently, the download from routeviews.org happens via FTP in the `pyasn_util_download.py`. However, in order to use HTTP proxies (mandatory in some requirements), HTTP is preferred or only possible.

**Comment by hadiasghari** [comment]
@wagner-certat if you have any PRs on this I'd be happy to merge :)

**Comment by wagner-certat** [comment]
In IntelMQ we now integrated the pyasn database update functionality, so there's no overlap of interest / potential of synergies. I therefore doubt that I'll provide a PR for this in the near future :/

**Comment by hadiasghari** [comment]
No problem. I'll close this for now, as I think some might also simply use wget. If there is interest in the future we can revisit this issue. Thanks!

**Comment by hadiasghari** [comment]
Hi @mansweet, thank you for the PR, I'll need a few days to get to this.

**Comment by hadiasghari** [comment]
@mansweet thank you for the commits. I approved and merged PR #69. Please send a new PR so I can run tests/check and then merge/approve. 

Note, regarding the feature list you mention, I agree with all, except this `I'll keep it simple and just add functionality to download the latest rib file, if that's alright`.  I feel this would make it unnecessary complicated that the FTP option can do different dates but the HTTP option only the latest. Would it be too difficult to allow different dates? (Since the date parsing option logic is already implemented).

Additionally, will it also support https downloads?

Thanks :)

**Comment by mansweet** [comment]
@hadiasghari  thanks for merging #69 and re-opening this issue. 

I agree with your request and think that there should be uniform functionality for different options.  However, correct me if I'm wrong, but it seems that the FTP path is only capable of downloading the latest, while the http (as of now) can download specific dates (with the `--dates-from-file` CLI arg).  I think my feature here is just adding functionality to download the latest from the `http` source without requiring the user to submit a file of dates in order to use the `http` path.

It might make sense then in a separate scope to to simplify the interface overall such that a user can:
- choose http vs ftp (or perhaps even https)
- choose that it just fetches the latest, or some specific dates for whatever download method. 


Now, as for the `https` downloads you've requested, I can look into that.  Can you provide me with what the source is that I should try to fetch the ribs from?  `https://archive.routeviews.org` does not resolve. 

I'll submit a PR shortly as it is now, but looking forward to continuing this conversation. 

Also, just an interesting find. Today is the 31st of August.  It looks like routeviews makes the directory for the next month perhaps a little bit early without populating it.  Just point this out in case you find some strange corner cases in the future!
![Screen Shot 2021-08-31 at 3 24 21 PM](https://user-images.githubusercontent.com/7752102/131583620-e22eedfd-ad58-4be1-81f5-dd48415b2885.png)

**Comment by mansweet** [comment]
hi @hadiasghari , any update on merging this PR?

**Comment by wagner-certat** [comment]
> Also, just an interesting find. Today is the 31st of August. It looks like routeviews makes the directory for the next month perhaps a little bit early without populating it. Just point this out in case you find some strange corner cases in the future!

That hit us in certtools/intelmq#2088 as well

**Comment by hadiasghari** [comment]
Hi @mansweet, thanks for the PR. I posted an update to the PR conversation, please see that.

@mansweet @wagner-certat regarding the last day of month edge case (which is probably a change on Routeviews side), we could go back one day if nothing is found in the current day.

**Comment by wagner-certat** [comment]
The monthly dirs are sorted here:
```
    months = sorted(ftp.nlst(archive_root), reverse=True)  # e.g. 'route-views6/bgpdata/2016.12'
```
We could also always use the current month, instead of just the newest directory.
